name: CI - Build, Test, and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Define Image Tag
      id: vars
      run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build Docker image with commit SHA tag
      run: docker build -t thedevopsforge/weather-cli-app:${TAG} .

    - name: Test Docker image
      run: docker run thedevopsforge/weather-cli-app:${TAG} Nairobi

    - name: Push Docker image
      run: docker push thedevopsforge/weather-cli-app:${TAG}
